// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC69JSbhCD_slgdyGeE8MrobG1nOHRz06o',
    appId: '1:162532943220:web:43a199c27b4916d7e73821',
    messagingSenderId: '162532943220',
    projectId: 'flutterchatapp-37879',
    authDomain: 'flutterchatapp-37879.firebaseapp.com',
    storageBucket: 'flutterchatapp-37879.appspot.com',
    measurementId: 'G-TD87G2QZS0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbNabxNL-JglxYzwelLUI2n6cJ18u0AVY',
    appId: '1:162532943220:android:89012e7d07c83e7ee73821',
    messagingSenderId: '162532943220',
    projectId: 'flutterchatapp-37879',
    storageBucket: 'flutterchatapp-37879.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSKWd3J0L0oHv3wy6vpnoEfeVWoD2hXJA',
    appId: '1:162532943220:ios:9cd6f163ed4f2b9ee73821',
    messagingSenderId: '162532943220',
    projectId: 'flutterchatapp-37879',
    storageBucket: 'flutterchatapp-37879.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSKWd3J0L0oHv3wy6vpnoEfeVWoD2hXJA',
    appId: '1:162532943220:ios:9cd6f163ed4f2b9ee73821',
    messagingSenderId: '162532943220',
    projectId: 'flutterchatapp-37879',
    storageBucket: 'flutterchatapp-37879.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC69JSbhCD_slgdyGeE8MrobG1nOHRz06o',
    appId: '1:162532943220:web:95ed0468d9b48267e73821',
    messagingSenderId: '162532943220',
    projectId: 'flutterchatapp-37879',
    authDomain: 'flutterchatapp-37879.firebaseapp.com',
    storageBucket: 'flutterchatapp-37879.appspot.com',
    measurementId: 'G-VCW8TJF6D8',
  );

}